# Define Application
app:
  replicas: 1
  image:
    pullPolicy: Always

# Environment Injection
ConfigMap:
  enabled: false
  data:
    - name: # NODE_ENV
      value: # "dev"

# Dynamic volumes
volumeMounts:
  enabled: false
  volumes:
    - name: # abc-volume
      mountPath: # /app
      emptyDir: # false # {}
      configMap: 
        name: # general-purpose-dynamic-env
        fromFile: # dev/config.json
        fileName: # config.json

# Ingress controller (Incoming Traffic from external)
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 25%

# Pod Resource
resources:
  limits:
    cpu: 150m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 150Mi
