# Define Application
app:
  replicas: 1
  image:
    registry: docker.io
    repository: #
    tag: latest
    pullPolicy: Always

# Define service
service:
  ports:
    - name: #
      port: 80
      targetPort: 80
      protocol: TCP

# Environment Injection
ConfigMap:
  enabled: false
  data:
    - name: #
      value: #

# Dynamic volumes
volumeMounts:
  enabled: false
  volumes:
    - name: # vol
      mountPath: # /mnt
      type: #
      spec: #

# Ingress controller (Incoming Traffic from external)
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 25%

# Pod Resource
resources:
  limits:
    cpu: 150m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 150Mi

# key Vault for public cloud provider
keyVault:
  enabled: false
  config:
    driver: secrets-store.csi.k8s.io
    provider: azure
    resourceGroup: #
    subscriptionId: #
    tenantId: #
    secretRef: #
    cloudName: AzurePublicCloud
    vaultName: #
  objects:
    - secretName: #
      type: Opaque
      data:
        - name: #
          key: #
