{{- if .Values.ConfigMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}--configmap
data:
  {{- if .Values.ConfigMap.data -}}
  {{- range $index, $value := .Values.ConfigMap.data }}
  {{ $value.name }}: {{ $value.value | quote }}
  {{- end }}
  {{- end -}}
{{- end }}

---

{{- if .Values.volumeMounts.enabled -}}

{{- $releaseName := .Release.Name -}}
{{- $files := .Files -}} # declare $files for use .Files.Get inside range
{{- range $index, $value := .Values.volumeMounts.volumes -}}

{{- if and $value.configMap (eq $value.emptyDir false) -}} # check existing configMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.configMap.name }}-{{ $releaseName }}--configmap
data:
  {{ $value.configMap.fileName }}: |-
{{ $files.Get $value.configMap.fromFile | indent 4 }}

{{- end -}}
{{- end -}}
{{- end -}}