{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.domainName | quote }}
      http:
        paths:
          {{-  $serviceName := .Release.Name -}}
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ if .backend.serviceName -}} {{ .backend.serviceName }} {{- else -}} {{ $serviceName }} {{- end }}
              servicePort: {{ .backend.servicePort }}
          {{- end }}
{{- end }}