{{- if .Values.ingress.tls  -}}
{{- if .Values.ingress.tls.cert -}}

{{ $path := printf "%s/%s" .Values.ingress.tls.cert.path .Values.ingress.tls.cert.fileName }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}--tls
type: kubernetes.io/tls
data:
{{ (.Files.Glob $path).AsSecrets | indent 2 }}

{{- end -}}
{{- end -}}