{{- if .Values.ConfigMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name | default .Release.Name }}--configmap
data:
  {{- if .Values.ConfigMap.data -}}
  {{- range $index, $value := .Values.ConfigMap.data }}
  {{ $value.name }}: {{ $value.value | quote }}
  {{- end }}
  {{- end -}}
{{- end }}

{{- if .Values.volumeMounts.enabled -}}

{{- $releaseName := .Values.app.name | default .Release.Name -}}
{{- $files := .Files -}} # declare $files for use .Files.Get inside range
{{- range $index, $value := .Values.volumeMounts.volumes -}}
{{- if eq $value.type "configMap" -}} # check volume type configMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.spec.name }}-{{ $releaseName }}--configmap
data:
  {{ $value.spec.fileName }}: |-
{{ if $value.spec.fromFile }}
{{ $files.Get $value.spec.fromFile | indent 4 }}
{{ else }}
{{ $value.spec.value | indent 4 }}
{{ end }}

{{- end -}}
{{- end -}}
{{- end -}}