{{- $values := .Values -}}
{{- if .Values.ingress.enabled -}}

{{- range $values.ingress.ingresses }}
{{ $paths := .paths -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  {{ if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{ end }}

  {{ if .defaultBackend }}
  defaultBackend:
    {{- toYaml .defaultBackend | nindent 4 }}
  {{ end }}

  tls:
  {{- range .http }}
  {{ if .tls }}
  {{ if .tls.cert }}
  {{ $tlssecret := printf "%s-%s" "tls" .tls.cert.name }}
    - secretName: {{ $tlssecret }}
      hosts:
        {{- toYaml .domainName | nindent 8 }}
  {{ else if .tls.existingSecret }}
    - secretName: {{ .tls.existingSecret }}
      hosts:
        {{- toYaml .domainName | nindent 8 }}
  {{ end }}
  {{ end }}
  {{ end -}}

  rules:
  {{- range .http }}
    {{- range .domainName }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ .backend.serviceName }}
                port: 
                  number: {{ .backend.servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{ end -}}