{{- $values := .Values -}}
{{- $file := .Files -}}
{{- if .Values.ingress.enabled  -}}
{{- range $values.ingress.ingresses }}
{{- range .http }}
{{ if .tls }}
{{ if .tls.cert }}
{{ $path := printf "%s/%s" .tls.cert.path .tls.cert.fileName }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" "tls" .tls.cert.name }}
type: kubernetes.io/tls
data:
{{ ($file.Glob $path).AsSecrets | indent 2 }}

{{ end }}
{{ end }}
{{- end }}
{{- end }}
{{- end -}}