app:
  image:
    registry: # docker.io
    repository: # nginx
    tag: dev
    pullPolicy: Always
    containerPort: 4200
  readinessProbe:
    enabled: false
    path: # /api/health
  envVolume:
    enabled: false
    name: # env-volume
    mountPath: # /app/src/assets/env/
    fileName: # config.json
    fromFile: # override/config.json

volumeMounts:
  enabled: false

service:
  ports:
    - name: # angular
      port: # 8080
      targetPort: # 4200
      protocol: # TCP

ingress:
  enabled: false
  domainName: # abc.example.com
  paths:
    - path: # /
      backend:
        servicePort: # 8080
  
ConfigMap:
  enabled: false
  data:
    - name: # NODE_ENV
      value: # "dev"